### ISSUE TITLE
Github service hook not working

### ISSUE THREAD

**Issue by lgaetz** [POSSA/freepbx-lenny_blacklist_mod#3]
@tm1000 
I set the webhook for this project the same as all the others, but the tarball didn't appear in /files as expected.  Not sure if I did something wrong or if you have to do something first for new projects to appear.

**Comment by tm1000** [comment]
I think I have to create the folders. Let me look at it tonight. If that is
true then I will make it so it forces the make of the folders.

Andrew Nagy
http://www.andrewsnagy.com
(951) 259 4723

**Comment by lgaetz** [comment]
I just updated the master branch again but still no tarball. Did you get a chance to address this?

**Comment by tm1000** [comment]
There were some old security restrictions that no longer applied to github. It works now

**Comment by lgaetz** [comment]
Thanks.
