### ISSUE TITLE
Bug - Module does not work if Blacklist has block anonymous calls enabled

### ISSUE THREAD

**Issue by lgaetz** [POSSA/freepbx-lenny_blacklist_mod#4]
Problem:
If blacklist has "Block Unknown/Blocked Caller ID" enabled, ver. 0.0.6 of the module does not work

Solution:
In order for this module to work, the alternate destination dialplan must be spliced after the Answer() command in the existing `app-blacklist-check` context. This could be on line 4 or it could be on line 8, depending on whether "Block Unknown/Blocked Caller ID" calls is enabled. The module dialplan could check for this condition and alter the splice commands as appropriate.

@tm1000 is this the only way to do this, is there another way to use the splice function so they go in after the Answer() line regardless of which number it is?

from admin/libraries/extension.class.php:

``` php
    /* This function allows new priorities to be injected into already generated dialplan
    *  usage: $ext->splice($context, $exten, $priority_number, new ext_goto('1','s','ext-did'));
    *         if $priority is not numeric, it will interpret it as a tag and try to inject 
    *         the command just prior to  the first instruction it finds with the specified tag
    *         if it can't find the tag, it will inject it after the last instruction
    */
    function splice($section, $extension, $priority, $command, $new_tag="", $offset=0, $fixmultiplelabels=false)  {

```

I am not sure how to use the offset, but my thinking is that I look for the priority (tag) "[Blacklisted]" and use an offset to insert the lines after that tag instead of before.

**Comment by kdain** [comment]
I can't get it to work at all. I read this link: http://nerdvittles.com/?p=6762
 and I used local/[53669]@from-internal as the destination. It won't let me type the less than and greater than symbols here, so I used [ and ] in the example.
I'm using Asterisk (Ver. 11.3.0), and FreePBX 2.11.0.10.

I blacklisted my cell phone to test, and I still get the SIT tone recording instead of Lenny.  
If I dial 53669 from an extension, Lenny is there.

-Kyle

**Comment by lgaetz** [comment]
Why the brackets around the digits in the destination? Make sure you are using the latest version of the Blacklist Mod, ver. 0.0.6. Make sure the "Enable redirect" is checked and the destination is `local/53669@from-internal` no characters around the digits are required.

**Comment by kdain** [comment]
Thanks for the quick reply!

the brackets were in the example surrounding the word "digits".  I tried it exactly as you said, and still no Lenny.

-K

**Comment by lgaetz** [comment]
Confirm that you are running ver. 0.0.6 of the module. With the module loaded, enabled and with the dialplan reloaded, give me the output from the CLI command `asterisk -rx "dialplan show app-blacklist-check"`

<del>Also where exactly do you see the example showing brackets around the digits, that needs to be fixed.</del> Found it in the readme.md file, now fixed.

**Comment by kdain** [comment]
It is 0.0.6.

```
[ Context 'app-blacklist-check' created by 'pbx_config' ]
  's' =>            1. GotoIf($["${CALLERID(number)}" = "Unknown"]?check-blocked) [pbx_config]
                    2. GotoIf($["${CALLERID(number)}" = "Unavailable"]?check-blocked) [pbx_config]
                    3. GotoIf($["foo${CALLERID(number)}" = "foo"]?check-blocked:check) [pbx_config]
     [check-blocked] 4. GotoIf($["${DB(blacklist/blocked)}" = "1"]?blacklisted) [pbx_config]
                    5. Dial(local/53669@from-internal,60,rL,240000) [pbx_config]
                    6. Hangup()                                   [pbx_config]
     [check]        7. GotoIf($["${BLACKLIST()}"="1"]?blacklisted) [pbx_config]
                    8. Set(CALLED_BLACKLIST=1)                    [pbx_config]
                    9. Return()                                   [pbx_config]
     [blacklisted]  10. Answer()                                  [pbx_config]
                    11. Wait(1)                                   [pbx_config]
                    12. Zapateller()                              [pbx_config]
                    13. Playback(ss-noservice)                    [pbx_config]
                    14. Hangup()                                  [pbx_config]
  Include =>        'app-blacklist-check-custom'                  [pbx_config]

-= 1 extension (14 priorities) in 1 context. =-
```

**Comment by lgaetz** [comment]
This is a legit bug with this module, not reported before. The Lenny Blacklist mod inserts 2 lines (or 3 if recording is enabled) of new dialplan after line 4 of the existing `app-blacklist-check` context.  Looking at Blacklist Mod code lines 71 and 72 [here](https://github.com/POSSA/freepbx-lenny_blacklist_mod/blob/master/functions.inc.php) you can see the dial plan is spliced after line 4 of the context. 

Unfortunately, the `app-blacklist-check` context on your machine contains additional lines that I had not tested for, because you have enabled "Block Unknown/Blocked Caller ID". The Blacklist mod dialplan needs to be inserted after the answer command which on my machine is line 4, but on your machine is line 8 (currently numbered 10 above, but would be 8 without this module installed).

Try disabling "Block Unknown/Blocked Caller ID" in the blacklist and see if that fixes things. If not, post your dialplan back here.

**Comment by kdain** [comment]
Lenny is alive :)  The unknown/blocked thing did it, however, I would still like to send unknown/blocked to Lenny.

Thanks so much!

-K

**Comment by lgaetz** [comment]
Until this module is fixed, the only way to have both the blacklist mod AND block anonymous calls enabled is to redefine the `app-blacklist-check` context manually in /etc/asterisk/extensions_override_freepbx.conf which will work but will override all the settings you make in the GUI for the Blacklist or the Blacklist Mod. You also have to remember you put it there because if you upgrade either module in the future, the changes you make in the override file will remain. Best to wait until we issue a fix for this bug.

**Comment by kdain** [comment]
ok, thanks so much!  also, I'm not a very good Linux coder, but I wrote this https://github.com/kdain/AutoYAC.

it doesn't work with the newest version of superfecta, but with a few edits, it does.  Maybe you could make it into something useful.

-K

**Comment by lgaetz** [comment]
I reviewed that code about an hour ago (and starred it). Please add your comments here:
https://github.com/POSSA/Caller-ID-Superfecta/issues/154

**Comment by kdain** [comment]
Thanks so much (again)  :)

**Comment by lgaetz** [comment]
@kdain  Try out version 0.0.7 and let me know if that fixes this issue:

http://pbxossa.org/files/lenny/lenny-0.0.7.tgz

Confirmed working for me on two 2.11 servers.

**Comment by kdain** [comment]
0.0.7 works with block anonymous/unknown checked. Thanks!

**Comment by lgaetz** [comment]
Note that this version will only work on FreePBX 2.11 and up. I need to investigate a fix for earlier versions.

**Comment by lgaetz** [comment]
Steps to fix for all versions:

For FreePBX versions less than 2.11, module needs to test to see if Blacklist blocked calls is enabled and add splice dialplan in two different places. For 2.11+ single splice will work with both cases.

To test for FreePBX version greater than 2.11:

``` php
// $foo will be -1 if version is older, 0 if version is same and 1 if version is newer
$foo = version_compare (getversion(),"2.11.0");
```

To test for Block anonymous calls enabled:

``` php
// $foo will be 1 if block enabled, 0 if not
$foo = $astman->database_get("blacklist","blocked") ;
```

**Comment by lgaetz** [comment]
The latest commit now tests for FreePBX version and writes out dialplan for both properly. If the FreePBX version check shows system is 2.10, the test for "Block anonymous calls" crashes the FreePBX reload every time. I don't know how (or if) I can properly test for this condition.
